spring.application.name=OPD_Management_Backend
spring.datasource.url=jdbc:mysql://localhost:3306/OPD_Management_System
spring.datasource.username=root
spring.datasource.password=ayan1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chikodeayan4@gmail.com
spring.mail.password=rvsbpqzcukasmrbv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#server.port=8081